version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build
          command: ./gradlew shadowJar
      - store_artifacts:
          path: build/libs/nitron-0.1-SNAPSHOT-all.jar
          destination: nitron.jar
      - run:
          name: Install Dependencies
          command: sudo apt-get install -y --fix-missing sqlite3
      - run:
          name: Test
          command: ./gradlew test
