version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install -y --fix-missing sqlite3
      - run:
          name: Test
          command: ./gradlew test
